// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr74-IIr9U4aDTLONQ98QuB52la_dM36I',
    appId: '1:298415847530:web:a28e38619c4f02acfd3213',
    messagingSenderId: '298415847530',
    projectId: 'flutterauthfirebase-a96ab',
    authDomain: 'flutterauthfirebase-a96ab.firebaseapp.com',
    storageBucket: 'flutterauthfirebase-a96ab.appspot.com',
    measurementId: 'G-6WG68YP1Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxqrfsuwpDjMVEnRWfDujIqzcYwvMdTwE',
    appId: '1:298415847530:android:5e4d98588b201a77fd3213',
    messagingSenderId: '298415847530',
    projectId: 'flutterauthfirebase-a96ab',
    storageBucket: 'flutterauthfirebase-a96ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEC1Zeozkt1VuN7OrNbQdWV0uzJD9GOFw',
    appId: '1:298415847530:ios:45b0cbb1d29aaf0efd3213',
    messagingSenderId: '298415847530',
    projectId: 'flutterauthfirebase-a96ab',
    storageBucket: 'flutterauthfirebase-a96ab.appspot.com',
    androidClientId: '298415847530-s9ri781lnprcqq91tb9op7fm0jpa9qvj.apps.googleusercontent.com',
    iosClientId: '298415847530-j2774cf4ggena29l13rc0vkgdql0ddfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApps',
  );
}
